name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this if your default branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t bitcoin-flask-app .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag bitcoin-flask-app ${{ secrets.DOCKER_USERNAME }}/bitcoin-flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bitcoin-flask-app:latest
